services:
  - type: web
    name: streamlit-scraper
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        value: your_gemini_api_key_here
    buildCommand: ""
    startCommand: ""
