services:
    - type: web
      name: selenium-flask-app
      env: python
      region: oregon
      buildCommand: "pip install -r requirements.txt"
      startCommand: "gunicorn -b 0.0.0.0:10000 test:app"
      envVars:
        - key: PORT
          value: "10000"
  
